-- SQL Script to Set Up Supabase Database

-- Enable UUID extension if needed (not strictly necessary if using auto-incrementing bigints, but good practice)
-- CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop tables if they exist (for easy re-running/setup)
DROP TABLE IF EXISTS customer_submissions;
DROP TABLE IF EXISTS stores;

-- Create stores table
CREATE TABLE stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create customer submissions table
CREATE TABLE customer_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    customer_name TEXT NOT NULL,
    mobile_number VARCHAR(10) NOT NULL,
    app_registration_status TEXT NOT NULL,
    invitation_card_issue BOOLEAN NOT NULL DEFAULT FALSE,
    issue_description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Ensure registration status matches predefined options
    CONSTRAINT chk_app_registration_status CHECK (app_registration_status IN ('Completed', 'Pending', 'Not Interested')),
    
    -- Ensure mobile number is exactly 10 digits
    CONSTRAINT chk_mobile_number CHECK (mobile_number ~ '^[0-9]{10}$')
);

-- Insert initial seed data for stores
INSERT INTO stores (store_name) VALUES
('Downtown Supermarket'),
('Metro Plaza Outlet'),
('Uptown Boutique'),
('Westside Hypermarket'),
('Suburban Groceries'),
('City Center Mart'),
('Green Valley Store')
ON CONFLICT (store_name) DO NOTHING;

-- Indexing for performance on dashboard filters/searches
CREATE INDEX idx_submissions_store_id ON customer_submissions(store_id);
CREATE INDEX idx_submissions_app_registration_status ON customer_submissions(app_registration_status);
CREATE INDEX idx_submissions_customer_name ON customer_submissions(customer_name);
CREATE INDEX idx_submissions_mobile_number ON customer_submissions(mobile_number);
