-- Idempotent Migration Script to Set Up Database Schema

-- Create stores table
CREATE TABLE IF NOT EXISTS stores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create customer entries table
CREATE TABLE IF NOT EXISTS customer_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id BIGINT NOT NULL REFERENCES stores(id) ON DELETE CASCADE,
    customer_name TEXT NOT NULL,
    mobile_number VARCHAR(10) NOT NULL,
    app_registration_status TEXT NOT NULL,
    invitation_issue BOOLEAN NOT NULL DEFAULT FALSE,
    issue_description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    -- Ensure registration status matches predefined options
    CONSTRAINT chk_app_registration_status CHECK (app_registration_status IN ('Completed', 'Pending', 'Not Interested')),
    
    -- Ensure mobile number is exactly 10 digits
    CONSTRAINT chk_mobile_number CHECK (mobile_number ~ '^[0-9]{10}$')
);

-- Insert initial seed data for stores
INSERT INTO stores (store_name) VALUES
('Bagepalli - 1 - (23rd Block, DVG Road)'),
('Chikkaballapur - 1 - (B B Road)'),
('Chintamani - 1 - (GSLN Theatre)'),
('Chintamani - 2 - (Minerva Stores)'),
('Dabaspete - 1 - (SMN Complex)'),
('Devanahalli - 1 - (19th Ward)'),
('Doddaballapur - 2 - (Lions Bhavana Complex)'),
('Gowribidnur - 1 - (P B Road)'),
('Gowribidnur - 2 - (NVR Complex)'),
('Nelamangala - 2 - (1st Block)'),
('Nelamangala - 1 - (Bus Stand)'),
('Sidlaghatta - 1 - (Near KSRTC Bus Stand)'),
('Vijayapura - 1 - (Opp. Police Station)')
ON CONFLICT (store_name) DO NOTHING;

-- Indexing for performance on dashboard filters/searches
CREATE INDEX IF NOT EXISTS idx_entries_store_id ON customer_entries(store_id);
CREATE INDEX IF NOT EXISTS idx_entries_app_registration_status ON customer_entries(app_registration_status);
CREATE INDEX IF NOT EXISTS idx_entries_customer_name ON customer_entries(customer_name);
CREATE INDEX IF NOT EXISTS idx_entries_mobile_number ON customer_entries(mobile_number);

-- Create audit logs table
CREATE TABLE IF NOT EXISTS delete_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name TEXT NOT NULL,
    user_role TEXT NOT NULL,
    delete_type TEXT NOT NULL,
    records_deleted INTEGER NOT NULL DEFAULT 0,
    details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
